# Generated by Django 2.2.4 on 2019-08-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_vocabulary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vocabulary',
        ),
    ]
